const movies = [
{name:"42", year:2013, length:0, genres:["history","sports","biopic"], type:["movie"], rating:null},
{name:"¡Three Amigos!", year:1986, length:0, genres:["comedy"], type:["movie"], rating:["bronze"]},
{name:"101 Dalmatians", year:1996, length:0, genres:["disney","family"], type:["movie"], rating:null},
{name:"102 Dalmatians", year:2000, length:0, genres:["disney","family"], type:["movie"], rating:null},
{name:"13th", year:2016, length:0, genres:["documentary"], type:["movie"], rating:null},
{name:"21 Jump Street", year:2012, length:0, genres:["comedy","crime"], type:["movie"], rating:null},
{name:"24 in 24: Last Chef Standing", year:2024, length:2, genres:["reality"], type:["tvshow"], rating:null},
{name:"30 Rock", year:2006, length:7, genres:["sitcom"], type:["tvshow"], rating:null},
{name:"3rd Rock From the Sun", year:1996, length:5, genres:["sitcom"], type:["tvshow"], rating:null},
{name:"A Beautiful Day in the Neighborhood", year:2019, length:0, genres:["drama","biopic"], type:["movie"], rating:null},
{name:"A Bug's Life", year:1998, length:0, genres:["disney","family","animation"], type:["movie"], rating:null},
{name:"A Charlie Brown Christmas", year:1965, length:0, genres:["christmas","animation"], type:["movie"], rating:null},
{name:"A Christmas Story", year:1983, length:0, genres:["christmas"], type:["movie"], rating:["silver"]},
{name:"A Complete Unknown", year:2024, length:0, genres:["biopic"], type:["movie"], rating:null},
{name:"A Goofy Movie", year:1995, length:0, genres:["top","disney","comedy","family","animation"], type:["movie"], rating:["gold"]},
{name:"A League of Their Own", year:1992, length:0, genres:["comedy","drama","sports"], type:["movie"], rating:null},
{name:"A Man Called Otto", year:2022, length:0, genres:["drama"], type:["movie"], rating:null},
{name:"A Man on the Inside", year:2025, length:2, genres:["comedy","mystery","crime"], type:["tvshow"], rating:null},
{name:"A Quiet Place", year:2018, length:0, genres:["horror"], type:["movie"], rating:null},
{name:"A Series of Unfortunate Events", year:2017, length:2, genres:["family","halloween"], type:["miniseries","tvshow"], rating:null},
{name:"Addams Family Values", year:1993, length:0, genres:["family","comedy","halloween"], type:["movie"], rating:null},
{name:"Adolescence", year:2025, length:0, genres:["drama","crime"], type:["miniseries"], rating:null},
{name:"Air", year:2023, length:0, genres:["sports"], type:["movie"], rating:null},
{name:"Air Bud", year:1997, length:0, genres:["family","sports"], type:["movie"], rating:null},
{name:"Air Bud: Golden Receiver", year:1998, length:0, genres:["sports"], type:["movie"], rating:null},
{name:"Air Bud: Seventh Inning Fetch", year:2002, length:0, genres:["sports"], type:["movie"], rating:null},
{name:"Air Bud: Spikes Back", year:2003, length:0, genres:["sports"], type:["movie"], rating:null},
{name:"Air Bud: World Pup", year:2000, length:0, genres:["sports"], type:["movie"], rating:null},
{name:"Aladdin", year:1992, length:0, genres:["musical","disney","family","animation"], type:["movie"], rating:["silver"]},
{name:"Alex vs America", year:2022, length:3, genres:["reality"], type:["tvshow"], rating:null},
{name:"Alice in Wonderland", year:1951, length:0, genres:["top","disney","family","fantasy","animation"], type:["movie"], rating:["gold"]},
{name:"Amadeus", year:1984, length:0, genres:["drama","history","biopic"], type:["movie"], rating:null},
{name:"American Horror Story", year:2011, length:14, genres:["horror","anthology"], type:["tvshow","miniseries"], rating:null},
{name:"An American Tail", year:1986, length:0, genres:["family","animation"], type:["movie"], rating:null},
{name:"Andor: A Star Wars Story", year:2022, length:3, genres:["starwars","scifi","drama","top","serial"], type:["tvshow"], rating:["gold"]},
{name:"Angels in the Outfield", year:1994, length:0, genres:["family","sports"], type:["movie"], rating:null},
{name:"Annie", year:1982, length:0, genres:["musical","family"], type:["movie"], rating:null},
{name:"Apollo 13", year:1995, length:0, genres:["drama","history"], type:["movie"], rating:null},
{name:"Arthur", year:1981, length:0, genres:["comedy"], type:["movie"], rating:null},
{name:"Aziz Ansari: Buried Alive", year:2013, length:0, genres:["standup"], type:["movie"], rating:null},
{name:"Aziz Ansari: Live at Madison Square Garden", year:2015, length:0, genres:["standup"], type:["movie"], rating:null},
{name:"Aziz Ansari: Right Now", year:2019, length:0, genres:["standup"], type:["movie"], rating:null},
{name:"Babe", year:1995, length:0, genres:["family"], type:["movie"], rating:null},
{name:"Back to the Future", year:1985, length:0, genres:["scifi","adventure","comedy"], type:["movie"], rating:["silver"]},
{name:"Back to the Future Part II", year:1989, length:0, genres:["scifi"], type:["movie"], rating:null},
{name:"Back to the Future Part III", year:1990, length:0, genres:["scifi","adventure"], type:["movie"], rating:null},
{name:"Barry", year:2018, length:5, genres:["comedy","crime"], type:["tvshow"], rating:null},
{name:"Batman", year:1966, length:0, genres:["adventure","action"], type:["movie"], rating:null},
{name:"Batman & Robin", year:1997, length:0, genres:["action","fantasy"], type:["movie"], rating:null},
{name:"Battle of the Sexes", year:2017, length:0, genres:["sports","history","biopic"], type:["movie"], rating:null},
{name:"Beat Bobby Flay", year:2013, length:13, genres:["reality"], type:["tvshow"], rating:null},
{name:"Beauty and the Beast", year:1991, length:0, genres:["disney","musical","family","romance","animation"], type:["movie"], rating:["bronze"]},
{name:"Beauty and the Beast: A 30th Celebration", year:2022, length:0, genres:["variety"], type:["movie"], rating:null},
{name:"Bedknobs and Broomsticks", year:1971, length:0, genres:["top","disney","musical","family","halloween"], type:["movie"], rating:["gold"]},
{name:"Beetlejuice", year:1988, length:0, genres:["comedy","halloween"], type:["movie"], rating:null},
{name:"Bel-Air", year:2022, length:4, genres:["drama"], type:["tvshow"], rating:null},
{name:"Better Call Saul", year:2015, length:7, genres:["drama","serial","crime"], type:["tvshow"], rating:["silver"]},
{name:"Bill Burr: Drop Dead Years", year:2025, length:0, genres:["standup"], type:["movie"], rating:null},
{name:"Bill Burr: Friends Who Kill", year:2022, length:0, genres:["standup"], type:["movie"], rating:null},
{name:"Bill Burr: I'm Sorry You Feel That Way", year:2014, length:0, genres:["standup"], type:["movie"], rating:null},
{name:"Bill Burr: Paper Tiger", year:2019, length:0, genres:["standup"], type:["movie"], rating:null},
{name:"Bill Burr: Walk Your Way Out", year:2017, length:0, genres:["standup"], type:["movie"], rating:null},
{name:"Billy Madison", year:1995, length:0, genres:["comedy"], type:["movie"], rating:null},
{name:"Black Mirror", year:2011, length:14, genres:["scifi","drama","anthology"], type:["tvshow"], rating:null},
{name:"BlacKKKlansman", year:2018, length:0, genres:["drama","comedy","crime","history"], type:["movie"], rating:["bronze"]},
{name:"Bob's Burgers", year:2011, length:15, genres:["comedy","top","family","sitcom","animation"], type:["tvshow"], rating:["gold"]},
{name:"Bohemian Rhapsody", year:2018, length:0, genres:["biopic"], type:["movie"], rating:null},
{name:"Boy Meets World", year:1993, length:7, genres:["sitcom"], type:["tvshow"], rating:null},
{name:"Brave", year:2012, length:0, genres:["disney","animation"], type:["movie"], rating:null},
{name:"Breaking Bad", year:2008, length:5, genres:["drama","top","serial","crime"], type:["tvshow"], rating:["gold"]},
{name:"Bridesmaids", year:2011, length:0, genres:["comedy"], type:["movie"], rating:null},
{name:"Bright Lights: Starring Carrie Fisher and Debbie Reynolds", year:2016, length:0, genres:["documentary"], type:["movie"], rating:null},
{name:"Brooklyn Nine-Nine", year:2013, length:8, genres:["comedy","sitcom"], type:["tvshow"], rating:null},
{name:"Cabin Fever", year:2002, length:0, genres:["horror"], type:["movie"], rating:null},
{name:"Caravan of Courage: The Ewok Adventure", year:1984, length:0, genres:["starwars","fantasy"], type:["movie"], rating:null},
{name:"Carrie Fisher: Wishful Drinking", year:2010, length:0, genres:["documentary","standup","biopic"], type:["movie"], rating:["bronze"]},
{name:"Casper", year:1995, length:0, genres:["halloween"], type:["movie"], rating:null},
{name:"Cast Away", year:2000, length:0, genres:["drama"], type:["movie"], rating:null},
{name:"Catch Me If You Can", year:2002, length:0, genres:["christmas","drama","crime"], type:["movie"], rating:null},
{name:"Champions", year:2023, length:0, genres:["sports"], type:["movie"], rating:null},
{name:"Charlie and the Chocolate Factory", year:2005, length:0, genres:["family"], type:["movie"], rating:["bronze"]},
{name:"Cheers", year:1982, length:11, genres:["comedy","top","sitcom"], type:["tvshow"], rating:["gold"]},
{name:"Chef", year:2014, length:0, genres:["comedy"], type:["movie"], rating:null},
{name:"Chernobyl", year:2019, length:0, genres:["drama","history"], type:["miniseries"], rating:null},
{name:"Chicago", year:2002, length:0, genres:["musical","crime"], type:["movie"], rating:["bronze"]},
{name:"Child's Play", year:1988, length:0, genres:["horror"], type:["movie"], rating:null},
{name:"Chip ‘n Dale: Rescue Rangers", year:2022, length:0, genres:["disney","family","crime"], type:["movie"], rating:null},
{name:"Chitty Chitty Bang Bang", year:1968, length:0, genres:["musical","family"], type:["movie"], rating:null},
{name:"Chopped", year:2009, length:16, genres:["reality"], type:["tvshow"], rating:null},
{name:"Christopher Robin", year:2018, length:0, genres:["disney","drama","family"], type:["movie"], rating:null},
{name:"Cinderella", year:1950, length:0, genres:["disney","family","animation"], type:["movie"], rating:null},
{name:"Class Action Park", year:2020, length:0, genres:["documentary"], type:["movie"], rating:null},
{name:"Clerks", year:1994, length:0, genres:["comedy"], type:["movie"], rating:null},
{name:"Clerks II", year:2006, length:0, genres:["comedy"], type:["movie"], rating:null},
{name:"Clerks III", year:2022, length:0, genres:["comedy"], type:["movie"], rating:null},
{name:"Clue", year:1985, length:0, genres:["comedy","halloween","mystery","crime"], type:["movie"], rating:["silver"]},
{name:"Coco", year:2017, length:0, genres:["disney","family","halloween","animation"], type:["movie"], rating:["bronze"]},
{name:"Community", year:2009, length:6, genres:["comedy","sitcom"], type:["tvshow"], rating:null},
{name:"Conan O'Brien Must Go", year:2021, length:3, genres:["reality"], type:["tvshow"], rating:null},
{name:"Conan Without Borders", year:2015, length:0, genres:["reality"], type:["tvshow"], rating:null},
{name:"Coraline", year:2009, length:0, genres:["halloween","animation"], type:["movie"], rating:null},
{name:"Cowboys & Aliens", year:2011, length:0, genres:["scifi","adventure","action"], type:["movie"], rating:["bronze"]},
{name:"Cruella", year:2021, length:0, genres:["family"], type:["movie"], rating:null},
{name:"Dateline", year:1992, length:34, genres:["mystery","crime","reality"], type:["tvshow"], rating:null},
{name:"David Holmes: The Boy Who Lived", year:2023, length:0, genres:["documentary"], type:["movie"], rating:null},
{name:"Derek DelGaudio's In & of Itself", year:2020, length:0, genres:["documentary","standup","variety","biopic"], type:["movie"], rating:["bronze"]},
{name:"Dinner for Schmucks", year:2010, length:0, genres:["comedy"], type:["movie"], rating:null},
{name:"Dinosaurs", year:1991, length:3, genres:["sitcom"], type:["tvshow"], rating:null},
{name:"Dirty Dancing", year:1987, length:0, genres:["top","drama","romance"], type:["movie"], rating:["gold"]},
{name:"Disney Gallery: The Mandalorian", year:2023, length:0, genres:["documentary"], type:["miniseries"], rating:null},
{name:"Disney's The Kid", year:2000, length:0, genres:["family"], type:["movie"], rating:null},
{name:"Dodgeball: A True Underdog Story", year:2004, length:0, genres:["comedy","sports"], type:["movie"], rating:null},
{name:"Dogma", year:1999, length:0, genres:["comedy"], type:["movie"], rating:null},
{name:"Donald Glover: Weirdo", year:2012, length:0, genres:["standup"], type:["movie"], rating:null},
{name:"Dopesick", year:2021, length:0, genres:["drama"], type:["miniseries"], rating:null},
{name:"DuckTales: The Movie – Treasure of the Lost Lamp", year:1990, length:0, genres:["disney","family","adventure","animation"], type:["movie"], rating:null},
{name:"Dumb and Dumber", year:1994, length:0, genres:["comedy"], type:["movie"], rating:null},
{name:"E.T. the Extra-Terrestrial", year:1982, length:0, genres:["top","scifi","fantasy","family","halloween"], type:["movie"], rating:["gold"]},
{name:"Elemental", year:2023, length:0, genres:["disney","family","animation"], type:["movie"], rating:null},
{name:"Elf", year:2003, length:0, genres:["christmas"], type:["movie"], rating:null},
{name:"Elvis", year:2022, length:0, genres:["biopic"], type:["movie"], rating:null},
{name:"Emmet Otter’s Jug-Band Christmas", year:1977, length:0, genres:["christmas"], type:["movie"], rating:null},
{name:"Empire of Dreams: The Story of the Star Wars Trilogy", year:2004, length:0, genres:["documentary","starwars"], type:["movie"], rating:["bronze"]},
{name:"Even Stevens", year:2000, length:3, genres:["sitcom"], type:["tvshow"], rating:null},
{name:"Everybody's Live with John Mulaney", year:2025, length:1, genres:["variety"], type:["tvshow"], rating:null},
{name:"Everything Everywhere All at Once", year:2022, length:0, genres:["scifi","action"], type:["movie"], rating:null},
{name:"Ewoks: The Battle for Endor", year:1985, length:0, genres:["starwars","family","scifi","fantasy"], type:["movie"], rating:null},
{name:"Family Guy", year:1999, length:27, genres:["comedy","sitcom","animation"], type:["tvshow"], rating:null},
{name:"Family Guy Presents: Blue Harvest", year:2007, length:0, genres:["comedy","animation"], type:["movie"], rating:["bronze"]},
{name:"Family Matters", year:1989, length:9, genres:["sitcom"], type:["tvshow"], rating:null},
{name:"Fanboys", year:2009, length:0, genres:["comedy"], type:["movie"], rating:["bronze"]},
{name:"Fantasia", year:1940, length:0, genres:["disney","musical","family","animation"], type:["movie"], rating:null},
{name:"Fantasia 2000", year:2000, length:0, genres:["disney","musical","family","animation"], type:["movie"], rating:null},
{name:"Fantastic Mr. Fox", year:2009, length:0, genres:["family","animation"], type:["movie"], rating:["bronze"]},
{name:"Father of the Bride", year:1991, length:0, genres:["comedy"], type:["movie"], rating:null},
{name:"FernGully: The Last Rainforest", year:1992, length:0, genres:["family","animation"], type:["movie"], rating:null},
{name:"Ferris Bueller’s Day Off", year:1986, length:0, genres:["comedy"], type:["movie"], rating:["silver"]},
{name:"Finding Nemo", year:2003, length:0, genres:["disney","family","animation"], type:["movie"], rating:null},
{name:"Fleabag", year:2023, length:2, genres:["comedy"], type:["miniseries"], rating:["silver"]},
{name:"Flow", year:2024, length:0, genres:["family","drama","animation"], type:["movie"], rating:["silver"]},
{name:"Fly Away Home", year:1996, length:0, genres:["drama","family"], type:["movie"], rating:null},
{name:"Forgetting Sarah Marshall", year:2008, length:0, genres:["comedy"], type:["movie"], rating:["bronze"]},
{name:"Forrest Gump", year:1994, length:0, genres:["drama"], type:["movie"], rating:["silver"]},

{name:"Freaks and Geeks", year:1999, length:1, genres:["comedy","drama","top"], type:["tvshow","miniseries"], rating:["silver"]},
{name:"Free Guy", year:2021, length:0, genres:["action"], type:["movie"], rating:null},
{name:"Free Willy", year:1993, length:0, genres:["family"], type:["movie"], rating:null},
{name:"Frozen", year:2013, length:0, genres:["disney","family","musical","animation"], type:["movie"], rating:null},
{name:"Full House", year:1987, length:8, genres:["sitcom"], type:["tvshow"], rating:null},
{name:"Futurama", year:1999, length:14, genres:["scifi","comedy","sitcom","animation"], type:["tvshow"], rating:null},
{name:"Galaxy Quest", year:1999, length:0, genres:["comedy","scifi"], type:["movie"], rating:null},
{name:"Game of Thrones", year:2011, length:8, genres:["drama","fantasy","serial"], type:["tvshow"], rating:["bronze"]},
{name:"Gary Gulman: Born on 3rd Base", year:2023, length:0, genres:["standup"], type:["movie"], rating:null},
{name:"Gary Gulman: Boyish Man", year:2005, length:0, genres:["standup"], type:["movie"], rating:null},
{name:"Gary Gulman: In This Economy?", year:2012, length:0, genres:["standup"], type:["movie"], rating:null},
{name:"Gary Gulman: It's About Time", year:2016, length:0, genres:["standup"], type:["movie"], rating:null},
{name:"Gary Gulman: The Great Depresh", year:2019, length:0, genres:["standup"], type:["movie"], rating:null},
{name:"Get Out", year:2017, length:0, genres:["horror"], type:["movie"], rating:null},
{name:"Get Smart", year:2008, length:0, genres:["comedy","crime"], type:["movie"], rating:null},
{name:"Ghostbusters", year:1984, length:0, genres:["comedy","halloween","scifi"], type:["movie"], rating:null},
{name:"Ghostbusters II", year:1989, length:0, genres:["comedy","halloween"], type:["movie"], rating:null},
{name:"Glass Onion", year:2019, length:0, genres:["drama","mystery","crime"], type:["movie"], rating:["bronze"]},
{name:"Groundhog Day", year:1993, length:0, genres:["comedy"], type:["movie"], rating:null},
{name:"Gulliver's Travels", year:1996, length:0, genres:["fantasy"], type:["miniseries"], rating:null},
{name:"Halloween", year:1978, length:0, genres:["horror"], type:["movie"], rating:null},
{name:"Hamilton", year:2020, length:0, genres:["musical","history"], type:["movie"], rating:["bronze"]},
{name:"Harry Potter and the Chamber of Secrets", year:2002, length:0, genres:["fantasy"], type:["movie"], rating:null},
{name:"Harry Potter and the Deathly Hallows: Part 1", year:2010, length:0, genres:["fantasy"], type:["movie"], rating:null},
{name:"Harry Potter and the Deathly Hallows: Part 2", year:2011, length:0, genres:["fantasy"], type:["movie"], rating:null},
{name:"Harry Potter and the Goblet of Fire", year:2005, length:0, genres:["fantasy"], type:["movie"], rating:null},
{name:"Harry Potter and the Half-Blood Prince", year:2009, length:0, genres:["fantasy"], type:["movie"], rating:null},
{name:"Harry Potter and the Order of the Phoenix", year:2007, length:0, genres:["fantasy"], type:["movie"], rating:null},
{name:"Harry Potter and the Prisoner of Azkaban", year:2004, length:0, genres:["fantasy"], type:["movie"], rating:null},
{name:"Harry Potter and the Sorcerer’s Stone", year:2001, length:0, genres:["fantasy","family"], type:["movie"], rating:["bronze"]},
{name:"Hasan Minhaj: Off With His Head", year:2024, length:0, genres:["standup"], type:["movie"], rating:null},
{name:"Hasan Minhaj: The King's Jester", year:2022, length:0, genres:["standup"], type:["movie"], rating:null},
{name:"Heavyweights", year:1995, length:0, genres:["comedy","family"], type:["movie"], rating:["bronze"]},
{name:"Hercules", year:1997, length:0, genres:["disney","musical","family","animation"], type:["movie"], rating:null},
{name:"Hocus Pocus", year:1993, length:0, genres:["halloween"], type:["movie"], rating:null},
{name:"Home Alone", year:1990, length:0, genres:["family","christmas","comedy"], type:["movie"], rating:["bronze"]},
{name:"Home Alone 2: Lost in New York", year:1992, length:0, genres:["christmas"], type:["movie"], rating:["bronze"]},
{name:"Home Improvement", year:1991, length:8, genres:["sitcom"], type:["tvshow"], rating:null},
{name:"Homeward Bound: The Incredible Journey", year:1993, length:0, genres:["family","adventure"], type:["movie"], rating:null},
{name:"Honey, I Blew Up the Kid", year:1992, length:0, genres:["family"], type:["movie"], rating:null},
{name:"Honey, I Shrunk the Kids", year:1989, length:0, genres:["family","scifi"], type:["movie"], rating:["bronze"]},
{name:"Honey, We Shrunk Ourselves", year:1997, length:0, genres:["family"], type:["movie"], rating:null},
{name:"Hook", year:1991, length:0, genres:["fantasy","family","christmas","adventure"], type:["movie"], rating:null},
{name:"Hotel Transylvania", year:2012, length:0, genres:["halloween","animation"], type:["movie"], rating:null},
{name:"House of the Dragon", year:2022, length:3, genres:["drama","fantasy","serial"], type:["tvshow"], rating:null},
{name:"How I Met Your Mother", year:2005, length:9, genres:["sitcom"], type:["tvshow"], rating:null},
{name:"How the Grinch Stole Christmas", year:2000, length:0, genres:["christmas"], type:["movie"], rating:null},
{name:"How the Grinch Stole Christmas!", year:1966, length:0, genres:["christmas","animation"], type:["movie"], rating:["bronze"]},
{name:"How to Train Your Dragon", year:2010, length:0, genres:["family","animation"], type:["movie"], rating:null},
{name:"I Think You Should Leave with Tim Robinson", year:2019, length:4, genres:["variety"], type:["tvshow"], rating:null},
{name:"Ilana Glazer: Human Magic", year:2025, length:0, genres:["standup"], type:["movie"], rating:null},
{name:"Ilana Glazer: The Planet is Burning        ", year:2020, length:0, genres:["standup"], type:["movie"], rating:null},
{name:"Iliza Shlesinger: A Different Animal", year:2025, length:0, genres:["standup"], type:["movie"], rating:null},
{name:"Iliza Shlesinger: Hot Forever", year:2022, length:0, genres:["standup"], type:["movie"], rating:null},
{name:"Impeachment: American Crime Story", year:2021, length:0, genres:["drama","crime"], type:["miniseries"], rating:null},
{name:"Indiana Jones and the Dial of Destiny", year:2023, length:0, genres:["scifi","fantasy","adventure","action"], type:["movie"], rating:["bronze"]},
{name:"Indiana Jones and the Kingdom of the Crystal Skull", year:2008, length:0, genres:["scifi","fantasy","adventure","action"], type:["movie"], rating:["bronze"]},
{name:"Indiana Jones and the Last Crusade", year:1989, length:0, genres:["fantasy","adventure","action"], type:["movie"], rating:["silver"]},
{name:"Indiana Jones and the Temple of Doom", year:1984, length:0, genres:["fantasy","adventure","action"], type:["movie"], rating:["silver"]},
{name:"Inside Out", year:2015, length:0, genres:["disney","family","animation"], type:["movie"], rating:null},
{name:"Inside Out 2", year:2024, length:0, genres:["disney","family","animation"], type:["movie"], rating:null},
{name:"It", year:2017, length:0, genres:["halloween","horror"], type:["movie"], rating:null},
{name:"It Chapter Two", year:2019, length:0, genres:["halloween","horror"], type:["movie"], rating:null},
{name:"It’s a Wonderful Life", year:1946, length:0, genres:["christmas","drama"], type:["movie"], rating:["bronze"]},
{name:"It's Always Sunny in Philadelphia", year:2005, length:21, genres:["comedy","sitcom"], type:["tvshow"], rating:null},
{name:"James and the Giant Peach", year:1996, length:0, genres:["family","musical","animation"], type:["movie"], rating:["silver"]},
{name:"Jaws", year:1975, length:0, genres:["drama","horror","adventure","action"], type:["movie"], rating:["bronze"]},
{name:"Jay and Silent Bob Reboot", year:2019, length:0, genres:["comedy"], type:["movie"], rating:null},
{name:"Jay and Silent Bob Strike Back", year:2001, length:0, genres:["comedy"], type:["movie"], rating:null},
{name:"Jerry & Marge Go Large", year:2022, length:0, genres:["comedy","crime"], type:["movie"], rating:null},
{name:"Jim Henson Idea Man", year:2024, length:0, genres:["documentary"], type:["movie"], rating:["bronze"]},
{name:"John Mulaney & the Sack Lunch Bunch", year:2019, length:0, genres:["variety"], type:["movie"], rating:null},
{name:"John Mulaney Presents: Everybody's in LA", year:2024, length:1, genres:["variety"], type:["tvshow"], rating:null},
{name:"John Mulaney: Baby J", year:2023, length:0, genres:["standup"], type:["movie"], rating:["silver"]},
{name:"John Mulaney: Kid Gorgeous at Radio City", year:2018, length:0, genres:["standup"], type:["movie"], rating:["silver"]},
{name:"John Mulaney: New in Town", year:2012, length:0, genres:["standup"], type:["movie"], rating:["silver"]},
{name:"John Mulaney: The Comeback Kid", year:2015, length:0, genres:["standup"], type:["movie"], rating:["silver"]},
{name:"John Oliver: Terrifying Times", year:2008, length:0, genres:["standup"], type:["movie"], rating:null},
{name:"John Oliver's New York Stand-Up Show", year:2010, length:2, genres:["variety","standup"], type:["tvshow"], rating:null},
{name:"John Williams in Tokyo", year:2024, length:0, genres:["variety"], type:["movie"], rating:null},
{name:"Jumanji", year:1995, length:0, genres:["family","fantasy","adventure","action"], type:["movie"], rating:["silver"]},
{name:"Jurassic Park", year:1993, length:0, genres:["top","scifi","adventure","action"], type:["movie"], rating:["gold"]},
{name:"Jurassic Park III", year:2001, length:0, genres:["scifi","adventure","action"], type:["movie"], rating:null},
{name:"Key & Peele", year:2012, length:3, genres:["variety"], type:["tvshow"], rating:null},
{name:"Kim's Convenience", year:2016, length:5, genres:["family","sitcom"], type:["tvshow"], rating:null},
{name:"King of Queens", year:1998, length:9, genres:["comedy","sitcom"], type:["tvshow"], rating:null},
{name:"King of the Hill", year:1997, length:13, genres:["comedy","sitcom","animation"], type:["tvshow"], rating:null},
{name:"Klaus", year:2019, length:0, genres:["christmas","animation"], type:["movie"], rating:null},
{name:"Knives Out", year:2019, length:0, genres:["drama","halloween","mystery","crime"], type:["movie"], rating:["gold"]},
{name:"Labyrinth", year:1986, length:0, genres:["fantasy","musical","halloween"], type:["movie"], rating:["bronze"]},
{name:"Ladies & Gentlemen... 50 Years of SNL Music", year:2025, length:0, genres:["documentary"], type:["movie"], rating:["bronze"]},
{name:"Lady and the Tramp", year:1955, length:0, genres:["disney","family"], type:["movie"], rating:null},
{name:"Last Man on Earth", year:2015, length:4, genres:["comedy"], type:["tvshow"], rating:null},
{name:"Last Week Tonight with John Oliver", year:2014, length:12, genres:["comedy","variety","top"], type:["tvshow"], rating:["gold"]},
{name:"Late Night with Seth Meyers", year:2014, length:12, genres:["variety"], type:["tvshow"], rating:null},
{name:"Late Show with Stephen Colbert", year:2015, length:10, genres:["variety"], type:["tvshow"], rating:null},
{name:"Law & Order", year:1990, length:20, genres:["drama","mystery","crime"], type:["tvshow"], rating:null},
{name:"Law & Order: Special Victims Unit", year:1999, length:27, genres:["drama","mystery","crime"], type:["tvshow"], rating:["silver"]},
{name:"LEGO Masters", year:2017, length:5, genres:["reality"], type:["tvshow"], rating:null},
{name:"LEGO Star Wars: Rebuild the Galaxy", year:2022, length:2, genres:["starwars","family","animation"], type:["tvshow","miniseries"], rating:null},
{name:"LEGO Star Wars: Terrifying Tales", year:2021, length:0, genres:["christmas","animation"], type:["movie"], rating:null},
{name:"Lessons in Chemistry", year:2023, length:0, genres:["drama"], type:["miniseries"], rating:null},
{name:"Liar Liar", year:1997, length:0, genres:["comedy"], type:["movie"], rating:null},
{name:"Light & Magic", year:2023, length:3, genres:["documentary","top"], type:["tvshow","miniseries"], rating:["gold"]},
{name:"Lilo & Stitch", year:2002, length:0, genres:["disney","family"], type:["movie"], rating:null},
{name:"Lincoln", year:2012, length:0, genres:["history","biopic"], type:["movie"], rating:null},
{name:"Little Shop of Horrors", year:1986, length:0, genres:["musical","comedy","halloween","horror"], type:["movie"], rating:["bronze"]},
{name:"Logan Lucky", year:2017, length:0, genres:["drama","comedy","crime"], type:["movie"], rating:null},
{name:"Luca", year:2021, length:0, genres:["disney","family","animation"], type:["movie"], rating:null},
{name:"MacGruber", year:2010, length:0, genres:["comedy"], type:["movie"], rating:null},
{name:"Malcolm in the Middle", year:2000, length:6, genres:["sitcom"], type:["tvshow"], rating:null},
{name:"Man of the House", year:1995, length:0, genres:["family"], type:["movie"], rating:null},
{name:"Man on the Moon", year:1999, length:0, genres:["biopic"], type:["movie"], rating:null},
{name:"Marc Maron: Panicked", year:2025, length:0, genres:["standup"], type:["movie"], rating:null},
{name:"Marcel the Shell with Shoes On", year:2021, length:0, genres:["drama","family"], type:["movie"], rating:["bronze"]},
{name:"Mary Poppins", year:1964, length:0, genres:["top","disney","musical","family"], type:["movie"], rating:["gold"]},
{name:"Master of None", year:2015, length:2, genres:["comedy"], type:["tvshow"], rating:null},
{name:"Matilda", year:1996, length:0, genres:["top","family"], type:["movie"], rating:["gold"]},
{name:"McMillion$", year:2020, length:0, genres:["documentary","crime"], type:["miniseries"], rating:null},
{name:"Men in Kilts", year:2023, length:2, genres:["documentary","history","reality"], type:["miniseries"], rating:null},
{name:"Michael Che Matters", year:2016, length:0, genres:["standup"], type:["movie"], rating:null},
{name:"Michael Clayton", year:2007, length:0, genres:["drama","crime"], type:["movie"], rating:["bronze"]},
{name:"Midsommar", year:2019, length:0, genres:["horror"], type:["movie"], rating:null},
{name:"Mike Birbiglia: My Girlfriend's Boyfriend", year:2013, length:0, genres:["standup"], type:["movie"], rating:null},
{name:"Mike Birbiglia: Thank God for Jokes", year:2017, length:0, genres:["standup"], type:["movie"], rating:null},
{name:"Mike Birbiglia: The New One", year:2019, length:0, genres:["standup"], type:["movie"], rating:null},
{name:"Mike Birbiglia: The Old Man and the Pool", year:2023, length:0, genres:["standup"], type:["movie"], rating:null},
{name:"Mike Birbiglia: What I Should Have Said Was Nothing", year:2008, length:0, genres:["standup"], type:["movie"], rating:null},
{name:"Minority Report", year:2002, length:0, genres:["action","scifi"], type:["movie"], rating:null},
{name:"Mission: Impossible", year:1997, length:0, genres:["action"], type:["movie"], rating:null},
{name:"Moana", year:2016, length:0, genres:["disney","musical","family","animation"], type:["movie"], rating:null},
{name:"Modern Family", year:2009, length:11, genres:["comedy","family","sitcom"], type:["tvshow"], rating:null},
{name:"Monsters, Inc.", year:2001, length:0, genres:["disney","family","animation"], type:["movie"], rating:null},
{name:"Mr. & Mrs. Smith", year:2023, length:3, genres:["comedy","drama","action","serial","crime"], type:["tvshow"], rating:["silver"]},
{name:"Mrs. Doubtfire", year:1993, length:0, genres:["comedy","family"], type:["movie"], rating:null},
{name:"Mulan", year:1998, length:0, genres:["disney","family","musical","animation"], type:["movie"], rating:null},
{name:"Muppets Haunted Mansion", year:2021, length:0, genres:["halloween"], type:["movie"], rating:null},
{name:"Music by John Williams", year:2024, length:0, genres:["documentary"], type:["movie"], rating:["silver"]},
{name:"My Big Fat Greek Wedding", year:2002, length:0, genres:["comedy"], type:["movie"], rating:null},
{name:"My Cousin Vinny", year:1992, length:0, genres:["top","comedy","crime"], type:["movie"], rating:["gold"]},
{name:"My Name is Earl", year:2005, length:4, genres:["comedy"], type:["tvshow"], rating:null},
{name:"My Next Guest Needs No Introduction with David Letterman", year:2018, length:7, genres:["variety"], type:["tvshow"], rating:null},
{name:"My Octopus Teacher", year:2020, length:0, genres:["documentary"], type:["movie"], rating:null},
{name:"Nate Bargatze: Full Time Magic", year:2015, length:0, genres:["standup"], type:["movie"], rating:null},
{name:"Nate Bargatze: Hello World", year:2023, length:0, genres:["standup"], type:["movie"], rating:null},
{name:"Nate Bargatze: The Greatest Average American", year:2021, length:0, genres:["standup"], type:["movie"], rating:null},
{name:"Nate Bargatze: The Tennessee Kid", year:2019, length:0, genres:["standup"], type:["movie"], rating:null},
{name:"Night at the Museum", year:2006, length:0, genres:["family","comedy"], type:["movie"], rating:null},
{name:"Nikki Glaser: Bangin'", year:2019, length:0, genres:["standup"], type:["movie"], rating:null},
{name:"Nikki Glaser: Good Clean Filth", year:2022, length:0, genres:["standup"], type:["movie"], rating:null},
{name:"Nikki Glaser: Perfect", year:2016, length:0, genres:["standup"], type:["movie"], rating:null},
{name:"Nikki Glaser: Someday You'll Die", year:2024, length:0, genres:["standup"], type:["movie"], rating:null},
{name:"Noelle", year:2019, length:0, genres:["christmas"], type:["movie"], rating:["bronze"]},
{name:"Not Just a Goof", year:2024, length:0, genres:["documentary"], type:["movie"], rating:null},
{name:"Ocean's Eleven", year:2001, length:0, genres:["drama","crime"], type:["movie"], rating:null},
{name:"Office Space", year:1999, length:0, genres:["comedy"], type:["movie"], rating:null},
{name:"Oh, Hello on Broadway", year:2017, length:0, genres:["variety"], type:["movie"], rating:null},
{name:"Oliver & Company", year:1988, length:0, genres:["disney","musical","family","animation"], type:["movie"], rating:["silver"]},
{name:"On the Basis of Sex", year:2018, length:0, genres:["history","biopic"], type:["movie"], rating:null},
{name:"One Hundred and One Dalmatians", year:1961, length:0, genres:["disney","family","animation"], type:["movie"], rating:["silver"]},
{name:"Only Murders in the Building", year:2021, length:5, genres:["comedy","mystery","crime"], type:["tvshow"], rating:null},
{name:"Operation Dumbo Drop", year:1995, length:0, genres:["family","history"], type:["movie"], rating:null},
{name:"Outlander", year:2014, length:12, genres:["drama","top","serial","romance","history"], type:["tvshow"], rating:["gold"]},
{name:"Outlander: Blood of My Blood", year:2015, length:2, genres:["drama","serial","romance"], type:["tvshow"], rating:["bronze"]},
{name:"Over the Garden Wall", year:2014, length:1, genres:["halloween","family","animation"], type:["tvshow","miniseries"], rating:null},
{name:"Ozark", year:2017, length:5, genres:["drama","serial","crime"], type:["tvshow"], rating:["silver"]},
{name:"Paddington", year:2014, length:0, genres:["family"], type:["movie"], rating:null},
{name:"Paddington 2", year:2017, length:0, genres:["family","crime"], type:["movie"], rating:["silver"]},
{name:"ParaNorman", year:2012, length:0, genres:["halloween","animation"], type:["movie"], rating:null},
{name:"Parks and Recreation", year:2009, length:7, genres:["comedy","sitcom"], type:["tvshow"], rating:["bronze"]},
{name:"Patton Oswalt: Annihilation", year:2017, length:0, genres:["standup"], type:["movie"], rating:null},
{name:"Patton Oswalt: I Love Everything", year:2020, length:0, genres:["standup"], type:["movie"], rating:null},
{name:"Patton Oswalt: Talking for Clapping", year:2016, length:0, genres:["standup"], type:["movie"], rating:null},
{name:"Patton Oswalt: We All Scream", year:2022, length:0, genres:["standup"], type:["movie"], rating:["bronze"]},
{name:"Pee-wee as Himself", year:2025, length:0, genres:["documentary","biopic"], type:["miniseries"], rating:null},
{name:"Pee-wee’s Big Adventure", year:1985, length:0, genres:["comedy","family"], type:["movie"], rating:["bronze"]},
{name:"Pepsi, Where’s My Jet?", year:2022, length:0, genres:["documentary"], type:["miniseries"], rating:null},
{name:"Pet Sematary", year:1989, length:0, genres:["horror"], type:["movie"], rating:null},
{name:"Pete Holmes: I Am Not for Everyone", year:2023, length:0, genres:["standup"], type:["movie"], rating:null},
{name:"Pete's Dragon", year:1977, length:0, genres:["disney","family"], type:["movie"], rating:null},
{name:"Pete's Dragon", year:2016, length:0, genres:["family"], type:["movie"], rating:null},
{name:"Peter Pan", year:1953, length:0, genres:["disney","family","animation"], type:["movie"], rating:["bronze"]},
{name:"Pinocchio", year:1940, length:0, genres:["disney","family","animation"], type:["movie"], rating:null},
{name:"Planet Earth", year:2006, length:0, genres:["documentary"], type:["miniseries"], rating:null},
{name:"Planet of the Apes", year:1968, length:0, genres:["scifi","drama"], type:["movie"], rating:["bronze"]},
{name:"Pocahontas", year:1995, length:0, genres:["musical","disney","family","animation"], type:["movie"], rating:["bronze"]},
{name:"Pokerface", year:2023, length:2, genres:["comedy","mystery","crime"], type:["tvshow"], rating:["silver"]},
{name:"Poltergeist", year:1982, length:0, genres:["horror"], type:["movie"], rating:null},
{name:"Portlandia", year:2011, length:7, genres:["variety"], type:["tvshow"], rating:null},
{name:"Psycho", year:1960, length:0, genres:["drama","halloween","horror"], type:["movie"], rating:null},
{name:"Raiders of the Lost Ark", year:1981, length:0, genres:["fantasy","adventure","action"], type:["movie"], rating:["silver"]},
{name:"Ratatouille", year:2007, length:0, genres:["disney","family","animation"], type:["movie"], rating:["silver"]},
{name:"Ready Player One", year:2018, length:0, genres:["scifi","action"], type:["movie"], rating:null},
{name:"Red Tails", year:2012, length:0, genres:["drama","action","history"], type:["movie"], rating:null},
{name:"Return to Oz", year:1985, length:0, genres:["fantasy"], type:["movie"], rating:null},
{name:"Rise of the Planet of the Apes", year:2011, length:0, genres:["scifi","drama"], type:["movie"], rating:null},
{name:"Robin Hood", year:1973, length:0, genres:["disney","family","animation"], type:["movie"], rating:["gold"]},
{name:"Robot Chicken: Star Wars", year:2007, length:10, genres:["variety","animation"], type:["tvshow"], rating:null},
{name:"Rocketman", year:2019, length:0, genres:["biopic"], type:["movie"], rating:null},
{name:"Rogue One: A Star Wars Story", year:2016, length:0, genres:["starwars","scifi"], type:["movie"], rating:["silver"]},
{name:"Role Models", year:2008, length:0, genres:["comedy"], type:["movie"], rating:null},
{name:"Romeo + Juliet", year:1996, length:0, genres:["drama","romance"], type:["movie"], rating:null},
{name:"Rookie of the Year", year:1993, length:0, genres:["sports"], type:["movie"], rating:null},
{name:"Rudolph the Red-Nosed Reindeer", year:1964, length:0, genres:["christmas","animation"], type:["movie"], rating:null},
{name:"Russian Doll", year:2019, length:3, genres:["comedy"], type:["tvshow"], rating:null},
{name:"Saturday Night", year:2024, length:0, genres:["biopic"], type:["movie"], rating:null},
{name:"Saturday Night Live", year:1975, length:55, genres:["comedy","variety","top"], type:["tvshow"], rating:["gold"]},
{name:"Saving Mr. Banks", year:2013, length:0, genres:["drama","family"], type:["movie"], rating:["bronze"]},
{name:"Scary Movie", year:2000, length:0, genres:["comedy","halloween","horror"], type:["movie"], rating:null},
{name:"Scream", year:1996, length:0, genres:["horror"], type:["movie"], rating:null},
{name:"Seth Meyers: Dad Man Walking", year:2024, length:0, genres:["standup"], type:["movie"], rating:null},
{name:"Seth Meyers: Lobby Baby", year:2019, length:0, genres:["standup"], type:["movie"], rating:null},
{name:"Shameless", year:2011, length:11, genres:["comedy","drama"], type:["tvshow"], rating:null},
{name:"Shaun of the Dead", year:2004, length:0, genres:["halloween","horror"], type:["movie"], rating:null},
{name:"Sherlock", year:2010, length:7, genres:["drama","mystery","top","serial","crime"], type:["tvshow","miniseries"], rating:["silver"]},
{name:"Shōgun", year:2023, length:3, genres:["drama","serial","history","action"], type:["tvshow","miniseries"], rating:["silver"]},
{name:"Show Me a Hero", year:2015, length:0, genres:["drama","crime"], type:["miniseries"], rating:null},
{name:"Shrek", year:2001, length:0, genres:["family","animation"], type:["movie"], rating:null},
{name:"Sister Act", year:1992, length:0, genres:["comedy","musical"], type:["movie"], rating:null},
{name:"Sleeping Beauty", year:1959, length:0, genres:["disney","family","animation"], type:["movie"], rating:["silver"]},
{name:"SNL50: The Homecoming Concert", year:2025, length:0, genres:["variety"], type:["movie"], rating:null},
{name:"Solo: A Star Wars Story", year:2018, length:0, genres:["starwars","scifi","top","adventure","action"], type:["movie"], rating:["gold"]},
{name:"Somebody Feed Phil", year:2018, length:7, genres:["reality"], type:["tvshow"], rating:null},
{name:"Soul", year:2020, length:0, genres:["disney","family","animation"], type:["movie"], rating:["silver"]},
{name:"South Park", year:1997, length:29, genres:["comedy","animation"], type:["tvshow"], rating:["bronze"]},
{name:"Space Jam", year:1996, length:0, genres:["sports"], type:["movie"], rating:null},
{name:"Spaceballs", year:1987, length:0, genres:["comedy","scifi"], type:["movie"], rating:null},
{name:"Spielberg", year:2017, length:0, genres:["documentary","biopic"], type:["movie"], rating:["bronze"]},
{name:"SpongeBob SquarePants", year:1999, length:26, genres:["family","animation"], type:["tvshow"], rating:null},
{name:"Stand By Me", year:1986, length:0, genres:["drama"], type:["movie"], rating:null},
{name:"Star Wars Visions", year:2021, length:4, genres:["starwars","anthology","animation"], type:["tvshow"], rating:null},
{name:"Star Wars: A New Hope", year:1977, length:0, genres:["starwars","scifi","fantasy","top"], type:["movie"], rating:["gold"]},
{name:"Star Wars: Attack of the Clones", year:2002, length:0, genres:["starwars","scifi","top"], type:["movie"], rating:["gold"]},
{name:"Star Wars: Obi-Wan Kenobi", year:2022, length:0, genres:["starwars","scifi","top"], type:["miniseries"], rating:["gold"]},
{name:"Star Wars: Return of the Jedi", year:1983, length:0, genres:["starwars","scifi","top"], type:["movie"], rating:["gold"]},
{name:"Star Wars: Revenge of the Sith", year:2005, length:0, genres:["starwars","scifi"], type:["movie"], rating:["silver"]},
{name:"Star Wars: Skeleton Crew", year:2023, length:2, genres:["starwars","family","top"], type:["miniseries","tvshow"], rating:["gold"]},
{name:"Star Wars: Starfighter", year:2027, length:0, genres:["starwars","scifi","adventure"], type:["movie"], rating:null},
{name:"Star Wars: The Acolyte", year:2025, length:0, genres:["starwars","mystery","top"], type:["miniseries","tvshow"], rating:["gold"]},
{name:"Star Wars: The Book of Boba Fett", year:2022, length:2, genres:["starwars","scifi"], type:["miniseries","tvshow"], rating:["bronze"]},
{name:"Star Wars: The Clone Wars", year:2008, length:12, genres:["starwars","scifi","animation"], type:["tvshow","movie"], rating:null},
{name:"Star Wars: The Empire Strikes Back", year:1980, length:0, genres:["starwars","scifi","top"], type:["movie"], rating:["gold"]},
{name:"Star Wars: The Force Awakens", year:2015, length:0, genres:["starwars","scifi","top"], type:["movie"], rating:["gold"]},
{name:"Star Wars: The Last Jedi", year:2017, length:0, genres:["starwars","scifi","top"], type:["movie"], rating:["gold"]},
{name:"Star Wars: The Mandalorian", year:2019, length:6, genres:["starwars","scifi","adventure","top"], type:["tvshow"], rating:["gold"]},
{name:"Star Wars: The Phantom Menace", year:1999, length:0, genres:["starwars","scifi","top"], type:["movie"], rating:["gold"]},
{name:"Star Wars: The Rise of Skywalker", year:2019, length:0, genres:["starwars","scifi"], type:["movie"], rating:["bronze"]},
{name:"Step Brothers", year:2008, length:0, genres:["comedy"], type:["movie"], rating:null},
{name:"Step by Step", year:1991, length:7, genres:["sitcom"], type:["tvshow"], rating:null},
{name:"Steve Martin and Martin Short: An Evening You Will Forget for the Rest of Your Life", year:2018, length:0, genres:["standup","variety"], type:["movie"], rating:null},
{name:"Stranger Things", year:2016, length:9, genres:["drama","scifi"], type:["tvshow"], rating:null},
{name:"Strays", year:2023, length:0, genres:["comedy"], type:["movie"], rating:null},
{name:"Stuart Little", year:1999, length:0, genres:["family"], type:["movie"], rating:null},
{name:"Succession", year:2018, length:5, genres:["drama","serial"], type:["tvshow"], rating:["silver"]},
{name:"Super Troopers", year:2001, length:0, genres:["comedy","crime"], type:["movie"], rating:null},
{name:"Superbad", year:2007, length:0, genres:["comedy"], type:["movie"], rating:null},
{name:"Swiss Family Robinson", year:1960, length:0, genres:["disney","family"], type:["movie"], rating:null},
{name:"Talladega Nights: The Ballad of Ricky Bobby", year:2006, length:0, genres:["comedy","sports"], type:["movie"], rating:null},
{name:"Tangled", year:2010, length:0, genres:["disney","family","musical","animation"], type:["movie"], rating:null},
{name:"Tarzan", year:1999, length:0, genres:["disney","family","musical","animation"], type:["movie"], rating:null},
{name:"Taylor Tomlinson: Have It All", year:2024, length:0, genres:["standup"], type:["movie"], rating:null},
{name:"Taylor Tomlinson: Look at You", year:2022, length:0, genres:["standup"], type:["movie"], rating:null},
{name:"Taylor Tomlinson: Quarter-Life Crisis", year:2020, length:0, genres:["standup"], type:["movie"], rating:null},
{name:"Ted", year:2012, length:0, genres:["comedy"], type:["movie"], rating:null},
{name:"The 40 Year-Old Virgin", year:2005, length:0, genres:["comedy"], type:["movie"], rating:["bronze"]},
{name:"The Addams Family", year:1991, length:0, genres:["family","comedy","halloween"], type:["movie"], rating:null},
{name:"The Adventures of Tintin", year:2011, length:0, genres:["family","adventure","mystery","crime","animation"], type:["movie"], rating:["bronze"]},
{name:"The Aristocats", year:1970, length:0, genres:["disney","family","animation"], type:["movie"], rating:null},
{name:"The Beginning: Making Episode I", year:2001, length:0, genres:["documentary"], type:["movie"], rating:null},
{name:"The BFG", year:2016, length:0, genres:["family"], type:["movie"], rating:["silver"]},
{name:"The Big Green", year:1995, length:0, genres:["family","sports"], type:["movie"], rating:null},
{name:"The Big Sick", year:2017, length:0, genres:["comedy","drama"], type:["movie"], rating:["bronze"]},
{name:"The Birds", year:1963, length:0, genres:["horror"], type:["movie"], rating:null},
{name:"The Boys: The Sherman Brothers' Story", year:2009, length:0, genres:["documentary","biopic"], type:["movie"], rating:null},
{name:"The Breakfast Club", year:1985, length:0, genres:["drama","comedy"], type:["movie"], rating:["bronze"]},
{name:"The Brothers Solomon", year:2007, length:0, genres:["comedy"], type:["movie"], rating:null},
{name:"The Chronicles of Narnia: Prince Caspian", year:2008, length:0, genres:["fantasy"], type:["movie"], rating:null},
{name:"The Chronicles of Narnia: The Lion, the Witch and the Wardrobe", year:2005, length:0, genres:["christmas","family","fantasy","adventure"], type:["movie"], rating:["silver"]},
{name:"The Chronicles of Narnia: The Voyage of the Dawn Treader", year:2010, length:0, genres:["fantasy","adventure"], type:["movie"], rating:null},
{name:"The Daily Show", year:1996, length:30, genres:["variety"], type:["tvshow"], rating:null},
{name:"The Director and the Jedi", year:2018, length:0, genres:["documentary"], type:["movie"], rating:null},
{name:"The Emperor’s New Groove", year:2000, length:0, genres:["disney","family"], type:["movie"], rating:["bronze"]},
{name:"The Fall of the House of Usher", year:2023, length:0, genres:["horror"], type:["miniseries"], rating:null},
{name:"The Fly", year:1986, length:0, genres:["horror"], type:["movie"], rating:null},
{name:"The Founder", year:2016, length:0, genres:["biopic"], type:["movie"], rating:null},
{name:"The Four Seasons", year:2023, length:0, genres:["comedy","drama"], type:["miniseries"], rating:null},
{name:"The Fresh Prince of Bel-Air", year:1990, length:6, genres:["sitcom"], type:["tvshow"], rating:null},
{name:"The Fugitive", year:1993, length:0, genres:["mystery","action","crime"], type:["movie"], rating:null},
{name:"The Goldbergs", year:2013, length:12, genres:["comedy","family","sitcom","top"], type:["tvshow"], rating:["gold"]},
{name:"The Good Dinosaur", year:2015, length:0, genres:["disney","family","animation"], type:["movie"], rating:null},
{name:"The Good Place", year:2016, length:4, genres:["comedy"], type:["tvshow"], rating:["silver"]},
{name:"The Goonies", year:1985, length:0, genres:["adventure","comedy"], type:["movie"], rating:["bronze"]},
{name:"The Great Escape", year:1963, length:0, genres:["drama","action","history"], type:["movie"], rating:["bronze"]},
{name:"The Great Mouse Detective", year:1986, length:0, genres:["disney","family","mystery","animation"], type:["movie"], rating:null},
{name:"The Great Muppet Caper", year:1980, length:0, genres:["family"], type:["movie"], rating:null},
{name:"The Grinch", year:2018, length:0, genres:["christmas","animation"], type:["movie"], rating:null},
{name:"The Holdovers", year:2023, length:0, genres:["christmas","drama"], type:["movie"], rating:["silver"]},
{name:"The Hunchback of Notre Dame", year:1996, length:0, genres:["disney","family","animation"], type:["movie"], rating:null},
{name:"The Incredibles", year:2004, length:0, genres:["disney","family","animation"], type:["movie"], rating:["silver"]},
{name:"The Iron Giant", year:1999, length:0, genres:["family","animation","scifi"], type:["movie"], rating:["silver"]},
{name:"The Jungle Book", year:1967, length:0, genres:["disney","family","animation"], type:["movie"], rating:null},
{name:"The Karate Kid", year:1984, length:0, genres:["sports"], type:["movie"], rating:null},
{name:"The Land Before Time", year:1988, length:0, genres:["family","animation"], type:["movie"], rating:null},
{name:"The Last Blockbuster", year:2020, length:0, genres:["documentary"], type:["movie"], rating:null},
{name:"The Last of Us", year:2023, length:3, genres:["drama"], type:["tvshow"], rating:null},
{name:"The Legend of Sleepy Hollow", year:1949, length:0, genres:["halloween","animation"], type:["movie"], rating:null},
{name:"The LEGO Star Wars Holiday Special", year:2020, length:0, genres:["halloween","animation"], type:["movie"], rating:null},
{name:"The Lion King", year:1994, length:0, genres:["disney","musical","family","top","animation"], type:["movie"], rating:["gold"]},
{name:"The Lion King 1½", year:2004, length:0, genres:["disney","family","animation"], type:["movie"], rating:null},
{name:"The Lion King at the Hollywood Bowl", year:2025, length:0, genres:["variety"], type:["movie"], rating:null},
{name:"The Little Mermaid", year:2023, length:0, genres:["disney","musical","family","animation"], type:["movie"], rating:["silver"]},
{name:"The Little Mermaid Live!", year:2019, length:0, genres:["variety"], type:["movie"], rating:null},
{name:"The Lord of the Rings: The Fellowship of the Ring", year:2001, length:0, genres:["fantasy","adventure"], type:["movie"], rating:null},
{name:"The Lord of the Rings: The Return of the King", year:2003, length:0, genres:["fantasy","adventure"], type:["movie"], rating:null},
{name:"The Lord of the Rings: The Two Towers", year:2002, length:0, genres:["fantasy","adventure"], type:["movie"], rating:null},
{name:"The Lost World: Jurassic Park", year:1997, length:0, genres:["scifi","action"], type:["movie"], rating:null},
{name:"The Mandalorian and Grogu", year:2026, length:0, genres:["starwars","scifi","adventure"], type:["movie"], rating:null},
{name:"The Many Adventures of Winnie the Pooh", year:1977, length:0, genres:["disney","family","animation"], type:["movie"], rating:["bronze"]},
{name:"The Matrix", year:1999, length:0, genres:["action","scifi"], type:["movie"], rating:null},
{name:"The Mick", year:2017, length:1, genres:["comedy","sitcom"], type:["tvshow"], rating:null},
{name:"The Mighty Ducks", year:1992, length:0, genres:["family","sports"], type:["movie"], rating:null},
{name:"The Mitchells vs. The Machines", year:2021, length:0, genres:["family","adventure","animation"], type:["movie"], rating:null},
{name:"The Money Pit", year:1986, length:0, genres:["comedy","top"], type:["movie"], rating:["gold"]},
{name:"The Movies That Made Us", year:2023, length:1, genres:["documentary"], type:["tvshow","miniseries"], rating:["silver"]},
{name:"The Mummy", year:1999, length:0, genres:["adventure","fantasy","action"], type:["movie"], rating:null},
{name:"The Muppet Christmas Carol", year:1992, length:0, genres:["christmas"], type:["movie"], rating:["silver"]},
{name:"The Muppet Movie", year:1979, length:0, genres:["family","musical"], type:["movie"], rating:null},
{name:"The Muppet Show", year:1974, length:5, genres:["variety"], type:["tvshow"], rating:null},
{name:"The Muppets", year:2011, length:0, genres:["family"], type:["movie"], rating:null},
{name:"The NeverEnding Story", year:1984, length:0, genres:["fantasy","adventure","family"], type:["movie"], rating:["silver"]},
{name:"The Night Of", year:2016, length:0, genres:["drama","mystery","crime"], type:["miniseries"], rating:null},
{name:"The Nightmare Before Christmas", year:1993, length:0, genres:["christmas","halloween","animation"], type:["movie"], rating:null},
{name:"The Office", year:2005, length:8, genres:["comedy","sitcom"], type:["tvshow"], rating:["bronze"]},
{name:"The Orville", year:2017, length:8, genres:["scifi","comedy","sitcom"], type:["tvshow"], rating:null},
{name:"The Other Guys", year:2010, length:0, genres:["comedy"], type:["movie"], rating:null},
{name:"The Outsider", year:2020, length:0, genres:["horror"], type:["miniseries"], rating:null},
{name:"The Paper", year:2025, length:2, genres:["comedy","sitcom"], type:["tvshow"], rating:null},
{name:"The Parent Trap", year:1961, length:0, genres:["disney","family"], type:["movie"], rating:null},
{name:"The Parent Trap", year:1998, length:0, genres:["disney","family"], type:["movie"], rating:null},
{name:"The People vs OJ Simpson: American Crime Story", year:2016, length:0, genres:["drama","crime","history"], type:["miniseries"], rating:null},
{name:"The Pit and the Pendulum", year:1961, length:0, genres:["halloween","horror"], type:["movie"], rating:null},
{name:"The Pixar Story", year:2007, length:0, genres:["documentary"], type:["movie"], rating:null},
{name:"The Polar Express", year:2004, length:0, genres:["christmas"], type:["movie"], rating:null},
{name:"The Princess and the Frog", year:2009, length:0, genres:["disney","family","animation"], type:["movie"], rating:null},
{name:"The Princess Bride", year:1987, length:0, genres:["top","family","fantasy","comedy","adventure","romance"], type:["movie"], rating:["gold"]},
{name:"The Queen's Gambit", year:2020, length:0, genres:["drama"], type:["miniseries"], rating:null},
{name:"The Rescuers Down Under", year:1990, length:0, genres:["disney","family","animation"], type:["movie"], rating:null},
{name:"The Residence", year:2025, length:0, genres:["comedy","mystery","crime"], type:["miniseries"], rating:null},
{name:"The Santa Clause", year:1994, length:0, genres:["christmas"], type:["movie"], rating:["silver"]},
{name:"The Secret Garden", year:1993, length:0, genres:["family","drama"], type:["movie"], rating:null},
{name:"The Shawshank Redemption", year:1994, length:0, genres:["drama","top","crime"], type:["movie"], rating:["gold"]},
{name:"The Shining", year:1980, length:0, genres:["horror"], type:["movie"], rating:null},
{name:"The Slammin' Salmon", year:2009, length:0, genres:["comedy"], type:["movie"], rating:null},
{name:"The Sound of Music", year:1965, length:0, genres:["top","musical","drama","family","romance"], type:["movie"], rating:["gold"]},
{name:"The Star Wars Holiday Special", year:1978, length:0, genres:["christmas"], type:["movie"], rating:null},
{name:"The Sword in the Stone", year:1963, length:0, genres:["disney","family","animation"], type:["movie"], rating:null},
{name:"The Terminal", year:2004, length:0, genres:["drama"], type:["movie"], rating:null},
{name:"The Toys That Made Us", year:2023, length:1, genres:["documentary"], type:["tvshow","miniseries"], rating:null},
{name:"The Twilight Zone", year:1959, length:5, genres:["scifi","halloween","anthology","horror"], type:["tvshow"], rating:["bronze"]},
{name:"The Twilight Zone", year:2019, length:2, genres:["scifi","halloween","anthology","horror"], type:["tvshow"], rating:null},
{name:"The Wild Robot", year:2024, length:0, genres:["family","scifi","animation"], type:["movie"], rating:["silver"]},
{name:"The Wilds", year:2020, length:2, genres:["drama"], type:["miniseries"], rating:null},
{name:"The Wizard of Oz", year:1939, length:0, genres:["musical","family","top"], type:["movie"], rating:["gold"]},
{name:"THX 1138", year:1971, length:0, genres:["scifi"], type:["movie"], rating:null},
{name:"Tig Notaro: Boyish Girl Interrupted", year:2015, length:0, genres:["standup"], type:["movie"], rating:null},
{name:"Tig Notaro: Happy to Be Here", year:2018, length:0, genres:["standup"], type:["movie"], rating:null},
{name:"Tig Notaro: Hello Again", year:2024, length:0, genres:["standup"], type:["movie"], rating:null},
{name:"Timeless Heroes: Indiana Jones & Harrison Ford", year:2023, length:0, genres:["documentary","biopic"], type:["movie"], rating:["bronze"]},
{name:"Titanic", year:1997, length:0, genres:["top","drama","romance","history"], type:["movie"], rating:["gold"]},
{name:"Tom and Huck", year:1995, length:0, genres:["family","adventure"], type:["movie"], rating:["silver"]},
{name:"Tommy Boy", year:1995, length:0, genres:["comedy"], type:["movie"], rating:null},
{name:"Tomorrowland", year:2015, length:0, genres:["scifi","adventure"], type:["movie"], rating:null},
{name:"Top Gun: Maverick", year:2022, length:0, genres:["drama","action"], type:["movie"], rating:["bronze"]},
{name:"Tournament of Champions", year:2020, length:5, genres:["reality"], type:["tvshow"], rating:null},
{name:"Toy Story", year:1995, length:0, genres:["top","disney","family","animation"], type:["movie"], rating:["gold"]},
{name:"Toy Story 2", year:1999, length:0, genres:["disney","family","animation"], type:["movie"], rating:["silver"]},
{name:"Toy Story 3", year:2010, length:0, genres:["top","disney","family","animation"], type:["movie"], rating:["gold"]},
{name:"Toy Story 4", year:2019, length:0, genres:["disney","family","animation"], type:["movie"], rating:["bronze"]},
{name:"Treasure Planet", year:2002, length:0, genres:["disney","family","animation","scifi"], type:["movie"], rating:null},
{name:"True Detective", year:2014, length:11, genres:["drama","mystery","crime"], type:["miniseries"], rating:null},
{name:"Under the Helmet: The Legacy of Boba Fett", year:2021, length:0, genres:["documentary"], type:["movie"], rating:["bronze"]},
{name:"Up", year:2009, length:0, genres:["disney","family","adventure","animation"], type:["movie"], rating:["silver"]},
{name:"Vikings", year:2013, length:7, genres:["history","serial"], type:["tvshow"], rating:null},
{name:"Waiting...", year:2005, length:0, genres:["comedy"], type:["movie"], rating:null},
{name:"Waking Sleeping Beauty", year:2009, length:0, genres:["documentary"], type:["movie"], rating:null},
{name:"Walk Hard: The Dewey Cox Story", year:2007, length:0, genres:["comedy","biopic"], type:["movie"], rating:null},
{name:"Wallace & Gromit: The Curse of the Were-Rabbit", year:2005, length:0, genres:["halloween","animation"], type:["movie"], rating:null},
{name:"WALL·E", year:2008, length:0, genres:["disney","family","scifi","animation"], type:["movie"], rating:["silver"]},
{name:"War of the Worlds", year:2005, length:0, genres:["scifi","action"], type:["movie"], rating:null},
{name:"WarGames", year:1983, length:0, genres:["drama","crime"], type:["movie"], rating:["bronze"]},
{name:"Wayne's World", year:1992, length:0, genres:["comedy"], type:["movie"], rating:null},
{name:"We Need to Talk About Cosby", year:2022, length:0, genres:["documentary"], type:["miniseries"], rating:null},
{name:"Weird: The Al Yankovic Story", year:2022, length:0, genres:["comedy","biopic"], type:["movie"], rating:["bronze"]},
{name:"Welcome to Chippendales", year:2022, length:0, genres:["drama","biopic"], type:["miniseries"], rating:["bronze"]},
{name:"West Side Story", year:2021, length:0, genres:["musical","romance"], type:["movie"], rating:null},
{name:"When They See Us", year:2019, length:0, genres:["history","crime"], type:["miniseries"], rating:null},
{name:"Where the Wild Things Are", year:2009, length:0, genres:["family"], type:["movie"], rating:null},
{name:"Who Framed Roger Rabbit", year:1988, length:0, genres:["disney","family","mystery","crime"], type:["movie"], rating:["silver"]},
{name:"Will & Harper", year:2024, length:0, genres:["documentary"], type:["movie"], rating:["bronze"]},
{name:"Willow", year:1988, length:0, genres:["fantasy","adventure"], type:["movie"], rating:null},
{name:"Willy Wonka and the Chocolate Factory", year:1971, length:0, genres:["top","musical","family"], type:["movie"], rating:["gold"]},
{name:"Winnie the Pooh", year:2011, length:0, genres:["disney","family","animation"], type:["movie"], rating:null},
{name:"Witness", year:1985, length:0, genres:["drama","mystery","crime"], type:["movie"], rating:["silver"]},
{name:"Won't You Be My Neighbor?", year:2018, length:0, genres:["documentary","biopic"], type:["movie"], rating:null},
{name:"Wonka", year:2023, length:0, genres:["top","musical","family","comedy","fantasy"], type:["movie"], rating:["gold"]},
{name:"Wreck-It Ralph", year:2012, length:0, genres:["disney","family","animation"], type:["movie"], rating:null},
{name:"Young Frankenstein", year:1975, length:0, genres:["comedy","halloween"], type:["movie"], rating:["silver"]},
{name:"Young Woman and the Sea", year:2024, length:0, genres:["drama","sports","history","biopic"], type:["movie"], rating:["bronze"]},
{name:"Your Friend, Nate Bargatze", year:2024, length:0, genres:["standup"], type:["movie"], rating:null},
{name:"Zathura: A Space Adventure", year:2005, length:0, genres:["scifi","fantasy","family"], type:["movie"], rating:null},
{name:"Zombieland", year:2009, length:0, genres:["halloween","horror"], type:["movie"], rating:null},
{name:"Zootopia", year:2016, length:0, genres:["disney","family","mystery","crime","animation"], type:["movie"], rating:["bronze"]},
];
